chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),

    path('<int:question_id>/', views.detail, name='detail'),
    # path('specifics/<int:question_id>/', views.detail, name='detail'),

    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

daihugo/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('AAA/', views.index_template, name='index_template'),
]

kslab_study/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),    # このディレクトリのviewsファイルを指定
    path('daihugo/', include('daihugo.urls')),  # 大富豪ディレクトリのurlsからviewsファイルを指定
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
import datetime

from django.db import models
from django.utils import timezone


class Room(models.Model):
    room_name = models.CharField(max_length=20)
    roomid = models.IntegerField(default=0)

    def __str__(self):
        return self.room_name


class Message(models.Model):
    message_text = models.CharField(max_length=200)
    sendtime = models.DateTimeField('date published')
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    def __str__(self):
        return self.message_text


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

daihugo/models.py
from django.db import models

# Create your models here.

chat/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

from .models import Question, Choice, Message
# Create your views here.


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'chat/index.html', context)


def room(request, room_name):
    message_list = Message.objects.order_by('-sendtime')[:5]
    context = {
        'room_name': room_name,
        'message_list': message_list
    }
    return render(request, 'chat/room.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'chat/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'chat/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'chat/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('chat:results', args=(question.id,)))

daihugo/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'daihugo/index.html') # ./templates/daihugo/index.htmlを参照

def index_template(request):
    ### 方法１
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # context = {'latest_question_list': latest_question_list}
    # return render(request, 'daihugo/index.html', context)

    ### 方法２
    # return render(request, 'index.html')

    ### 方法３
    return HttpResponse("大富豪ページへようこそ.（ここに直接書き込むのもあり?）")

kslab_study/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'kslab_study/index.html')

chat/templates/chat/detail.html
<!-- {{ question }} -->
<!-- <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->

<form action="{% url 'chat:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Chat Rooms</title>
  </head>
  <body>
    What chat room would you like to enter?<br />
    <input id="room-name-input" type="text" size="100" /><br />
    <input id="room-name-submit" type="button" value="Enter" />
    
    

    {% if latest_question_list %}
      <ul>
      {% for question in latest_question_list %}
        <!-- <li><a href="/chat/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'chat:detail' question.id %}">{{ question.question_text }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}





    <script>
      document.querySelector("#room-name-input").focus();
      document.querySelector("#room-name-input").onkeyup = function (e) {
        if (e.keyCode === 13) {
          // enter, return
          document.querySelector("#room-name-submit").click();
        }
      };

      document.querySelector("#room-name-submit").onclick = function (e) {
        var roomName = document.querySelector("#room-name-input").value;
        window.location.pathname = "/chat/" + roomName + "/";
      };
    </script>
  </body>
</html>

chat/templates/chat/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'chat:detail' question.id %}">Vote again?</a>

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Chat Room</title>
  </head>
  <body>
    <textarea id="chat-log" cols="100" rows="20">{% if message_list %}{% for message in message_list %}{{ message.sendtime }}:    {{ message.message_text }}
{% endfor %}{% else %}{% endif %}</textarea><br />
    <input id="chat-message-input" type="text" size="100" /><br />
    <input id="chat-message-submit" type="button" value="Send" />
    {{ room_name|json_script:"room-name" }}


    <script>
      const roomName = JSON.parse(
        document.getElementById("room-name").textContent
      );

      const chatSocket = new WebSocket(
        "wss://" + window.location.host + "/wss/chat/" + roomName + "/"
      );

      chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        document.querySelector("#chat-log").value += data.message + "\n";
      };

      chatSocket.onclose = function (e) {
        console.error("Chat socket closed unexpectedly");
      };

      document.querySelector("#chat-message-input").focus();
      document.querySelector("#chat-message-input").onkeyup = function (e) {
        if (e.keyCode === 13) {
          // enter, return
          document.querySelector("#chat-message-submit").click();
        }
      };

      document.querySelector("#chat-message-submit").onclick = function (e) {
        const messageInputDom = document.querySelector("#chat-message-input");
        const message = messageInputDom.value;
        chatSocket.send(
          JSON.stringify({
            message: message,
          })
        );
        messageInputDom.value = "";
      };
    </script>
  </body>
</html>

daihugo/templates/daihugo/components/left_side_bar.html
<aside class="left-side-bar">
    <h2>左サイドバー<br/>ここいります</h2>
</aside>

daihugo/templates/daihugo/components/right-side-bar.html
<aside class="right-side-bar">
    <h2>右サイドバー</h2>
    何に使おう？チャットとか？
</aside>

daihugo/templates/daihugo/index.html
{% extends 'base.html' %}
<!-- 継承元を指定 -->
{% load static %}

<!-- head部分 -->
{% block title %} 大富豪トップページ {% endblock %}
<!-- CSS -->
{% block CSS %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'daihugo/css/style.css' %}"
/>
{% endblock %}

<!-- body部分 -->
{% block header %}
<header>
  <h1>大富豪ページへようこそ</h1>
</header>
{% endblock %} {% block main %}
<div class="flex-row">
  <!-- includeはtemplateの中を確認！ -->
  {% include 'daihugo/components/left_side_bar.html' %}

  <main>メインの場所 devブランチで編集中</main>

  <!-- includeはtemplateの中を確認！ -->
  {% include 'daihugo/components/right-side-bar.html' %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="{% block meta_description %} メタ詳細部分 {% endblock %}" />
    <!-- favicon -->
    <link
      rel="icon"
      type="image/png"
      href="{% static 'kslab_study/favicon/thumb.png' %}"
    />

    <title>{% block title %}KSL 練習台{% endblock %}</title>
    <!-- CSS -->
    {% block CSS %}
      <link
        rel="stylesheet"
        type="text/css"
        href="{% static 'kslab_study/css/style.css' %}"
      />
    {% endblock %}
  </head>

  <body>
    {% block header %}
      <header>
        <h1>大富豪サイトへようこそ</h1>
      </header>
    {% endblock %}

    {% block main %}
      <main>
        <p>デフォルトの文字列が表示されています.</p>
        <p>それぞれのファイルでオーバーライドしてください</p>
        この文字列はkslab_study/templates/base.html のものです<br />
      </main>
    {% endblock %}

    {% block footer %}
    <footer>
      <p>&copy; 名前_____. 2021.</p>
    </footer>
    {% endblock %}

  </body>
</html>

templates/kslab_study/index.html
{% extends 'base.html' %}
<!-- 継承元を指定 -->
{% load static %}

<!-- head部分 -->
{% block meta_description %}あああああ{% endblock %} {% block title %}
オーバーライドしたタイトル {% endblock %} {% block CSS %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'kslab_study/css/style.css' %}"
/>
{% endblock %}

<!-- body部分 -->

{% block main %}
<main>
  <p>トップページ.</p>
  <br />
  このファイルはkslab_study/templates/kslab_study/index.html<br />
  <button onclick="location.href='./daihugo'">大富豪</button>
  <button onclick="location.href='./chat'">チャット(ソケット通信 確認用)</button>
</main>
{% endblock %}